services:
  neo4j:
    image: neo4j:5.18
    environment:
      - NEO4J_AUTH=neo4j/strongpass123
    ports:
      - "7474:7474"
      - "7687:7687"
    volumes:
      - neo4j_data:/data

  app:
    build: .
    environment:
      - NEO4J_URI=bolt://neo4j:7687
      - NEO4J_USER=neo4j
      - NEO4J_PASSWORD=strongpass123
      - GROQ_API_KEY=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
    ports:
      - "8501:8501"
    volumes:
      - ./outputs:/app/outputs
    depends_on:
      - neo4j
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  neo4j_data:
